set -g @catppuccin_flavor "mocha"

# Window format: number(command), centered
set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_default_fill "none"
set -g @catppuccin_window_current_fill "none"
set -g status-justify centre

set -g status-right-length 100
set -g status-left-length 100
set -g status-left "#{E:@catppuccin_status_session}"
set -g @catppuccin_directory_text " #{s|$HOME|~|:pane_current_path}"
set -g status-right ""
set -agF status-right "#{E:@catppuccin_status_directory}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_ram}"

run ~/.tmux/plugins/tmux-cpu/cpu.tmux
run ~/.config/tmux/plugins/tmux-plugins/tmux-cpu/cpu.tmux
run ~/.config/tmux/plugins/tmux-plugins/tmux-battery/battery.tmux
